name: Build & Check Bridge

on:
  push:
    paths:
      - 'apps/desktop-daemon/**'
      - '.github/workflows/**'
      - 'flake.nix'
  pull_request:
    paths:
      - 'apps/desktop-daemon/**'
      - '.github/workflows/**'
      - 'flake.nix'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: apps/desktop-daemon
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libglib2.0-dev libgtk-3-dev libdbus-1-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev libayatana-appindicator3-dev libxdo-dev
      - name: cargo check
        run: cargo check --bin synthhires-bridge
      - name: cargo test
        run: cargo test

  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Check & build with Nix Flake
        run: nix build -L
